### ISSUE TITLE
 AttributeError: 'RedisConnection' object has no attribute 'get'

### ISSUE THREAD

**Issue by ZhukovGreen** [cr0hn/aiohttp-cache#5]
Hello,

when running the aiohttp app I have the following error:
```
File "/usr/local/lib/python3.7/site-packages/aiohttp_cache/backends.py", line 117, in get
redis_value = await redis.get(self.key_prefix + key)
AttributeError: 'RedisConnection' object has no attribute 'get'
```

**Comment by didoogan** [comment]
Same issue when redis is used:

def init_web_app():
    try:
        app = web.Application(debug=True, middlewares=[])
        setup_routes(app)
        redis_config = RedisConfig(db=4, host='redis', port=6379, key_prefix='clients')
        setup_cache(app, cache_type='redis', backend_config=redis_config)
    except Exception as e:
        print(e)
web.run_app(init_web_app())

**Comment by nobbynobbs** [comment]
Hi! Is it fixed in release version?

**Comment by ZhukovGreen** [comment]
yes, it is fixed

**Comment by nobbynobbs** [comment]
@ZhukovGreen 

Sorry, could you explain me one moment. Is fixed version published on pypi? I've just install aiohttp-cache with poetry and run into this problem. And as I can see the latest version of library was published on [pypi](https://pypi.org/project/aiohttp-cache/) on Aug 8, 2018 year, even before this issue was opened. Should I use github link for installation or something like that?

**Comment by ZhukovGreen** [comment]
hi Roman @nobbynobbs,
I am sorry for the confussion.

Could you check if it works with the following line in pyproject.toml:
```toml
[tool.poetry.dependencies]
aiohttp-cache = {git = "https://github.com/cr0hn/aiohttp-cache.git", rev = "9670a3d42ccadd959ec460e2a4e20bfa01ffa295"}
```

**Comment by nobbynobbs** [comment]
Thanks, it works, but I've been forced to install aioredis manually, poetry didn't resolve dependency. I don't know, maybe it's poetry issue or special for installing from git.

**Comment by ZhukovGreen** [comment]
@nobbynobbs you might try the recent poetry, I guess it is 1.0.0b9 or so. Let's see the behaviour after #14 will be merged

**Comment by nobbynobbs** [comment]
Oh, poetry just released version 1.0.0, and it's not the beta anymore. But it has the same behavior, and wants `aioredis` in dependencies for `aiohttp-cache` installations from git.

Btw, I'm not hurry with this, just writing a toy project for practice with `aiohttp`.

**Comment by anmv** [comment]
How I can use this library now, if don't have poetry?

**Comment by ZhukovGreen** [comment]
@anmv You don't need to have poetry installed, you can pip install the pkg, but pip version should be ^19.1

**Comment by anmv** [comment]
@ZhukovGreen I getting error: `AttributeError: 'RedisConnection' object has no attribute 'get'` when I using `@cache` decorator
```
My environments:
MacOs: 10.15.2 Catalina
Python: 3.8
pip: 19.3.1
setuptools: 42.0.2
```

**Comment by ZhukovGreen** [comment]
@anmv what means basically that the lates MR #14 fixes the problem and working normally with pip:) (/cc @cr0hn )

**Comment by ZhukovGreen** [comment]
btw @anmv you should use in your requirements.txt a bit different version:
```
git+https://github.com/cr0hn/aiohttp-cache.git@744455b53aaf6125667413c48576887826ff853d
```
